import "./globals.css";
import { DM_Sans } from "next/font/google";
import { cn } from "@/lib/utils";

const ds_Sans = DM_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "IE | House of SiRa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          ds_Sans.className,
          "antialiased bg-[#EAEEFE] min-h-screen"
        )}
      >
        {children}
      </body>
    </html>
  );
}
