import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "IE | House of SiRa",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children }: Props) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
