import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
// import "./globals.css";
import { cn } from "@/lib/utils";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

const ds_Sans = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "IE | House of SiRa",
  description: "Generated by create next app",
};
type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};
export default async function LocaleLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang="en">
      <body className={cn(ds_Sans.className, "antialiased bg-[#EAEEFE]")}>
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
