import "@/app/globals.css";
import { DM_Sans } from "next/font/google";
import { cn } from "@/lib/utils";
import { Header } from "@/components/header/Header";

const ds_Sans = DM_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Blogs | House of SiRa",
  description: "Generated by create next app",
};

export default function BlogLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      className={cn(ds_Sans.className, "antialiased bg-[#EAEEFE] min-h-screen")}
    >
      <Header />
      {children}
    </div>
  );
}
